name: liftoff
description: A mobile client for Lemmy - a federated reddit alternative

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.10.10+32

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  # widgets
  flutter_speed_dial: ^7.0.0
  photo_view: ^0.14.0
  markdown: ^7.1.0
  flutter_markdown: ^0.6.1
  flutter_typeahead: ^4.0.0
  modal_bottom_sheet: ^3.0.0-pre
  swipeable_page_route: ^0.4.0
  infinite_scroll_pagination: ^3.2.0

  # native
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.0.5
  package_info_plus: ^4.0.2
  image_picker: ^0.8.4
  extended_image: ^8.0.2
  image_editor: ^1.3.0  
  gallery_saver: ^2.3.2
  flutter_cache_manager: ^3.3.0
  permission_handler: ^10.4.0

  # state management
  flutter_hooks: ^0.18.0
  provider: ^6.0.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  # utils
  timeago: ^3.0.2
  fuzzy: ^0.4.0-nullsafety.0
  lemmy_api_client:
    git:
      url: https://github.com/liftoff-app/lemmy_api_client.git
      ref: master
    # path: ../lemmy_api_client
  intl: ^0.18.0
  matrix4_transform: ^2.0.0
  json_annotation: ^4.8.1
  keyboard_dismisser: ^3.0.0
  freezed_annotation: ^2.0.1
  logging: ^1.0.1
  nested: ^1.0.0
  l10n_esperanto: ^2.0.5
  uuid: ^3.0.7

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wc_form_validators: ^1.0.0
  file_picker: ^5.3.2
  double_back_to_close_app: ^2.1.0
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.0.15
  path: ^1.8.3
  image: ^4.0.17
  app_links: ^3.4.3
  flutter_custom_tabs: ^1.0.4
  http: ^0.13.6
  video_player: ^2.7.0
  collection: ^1.17.1

# https://github.com/flutter/flutter/issues/127425
dependency_overrides:
  markdown: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.0.0
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.2
  freezed: ^2.0.2
  flutter_lints: ^2.0.2

# To refresh: `pub run flutter_launcher_icons`
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/adaptive_icon_fg.png
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - PRIVACY_POLICY.md
    - assets/app_icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
