name: weblate

on:
  workflow_dispatch:
  schedule:
    # every friday at 19:00 UTC
    - cron: "0 19 * * 5"

jobs:
  weblate:
    name: Pull Weblate changes to repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch changes
        run: |
          git remote add weblate https://weblate.yerbamate.ml/git/lemmur/lemmur/
          git fetch weblate
          git merge weblate/master

      - name: Regenerate l10n_from_string
        run: |
          dart run scripts/gen_l10n_from_string.dart

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          reviewers: shilangyu,krawieck
          title: Weblate update
          branch: weblate
